### ISSUE TITLE
Repeating characters / Unique characters rules overlap

### ISSUE THREAD

**Issue by zgael** [troyhunt/password-purgatory#7]
Hi there,
It seems to me that there is no way I can fulfill both conditions that lead to the following error messages : 

Password must contain repeating characters.
Password must contain only unique characters.

So I'm unable to reach the Ridiculous Infuriation Level, which makes me pretty sad :(

Maybe such "nemesis" rules shouldn't be allowed together, or maybe I'm missing something to satisfy both ?

**Comment by troyhunt** [comment]
Yep, good point, now fixed: https://github.com/troyhunt/password-purgatory-api/commit/b2c5d3266e11d970f0c96ec1d0f467edc3553470
